import Head from 'next/head'
import About from '../components/About'
import BestGpu from '../components/BestGpu'
import Hero from '../components/Hero'
import Menu from '../components/Menu'
import SellThings from '../components/SellThings'
import "react-responsive-carousel/lib/styles/carousel.min.css";
import styles from '../styles/Home.module.css'
import Service from '../components/Service'
import Contact from '../components/Contact'
import Newsletter from '../components/Newsletter'
import Footer from '../components/Footer'
import Customers from '../components/Customers'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <Hero  />
      <Service  />
      <About />
      {/* <SellThings /> */}
      {/* <BestGpu /> */}
      <Contact id="contact"/>
      <Customers />
      {/* <Newsletter  /> */}
      <Footer />
      
    </div>
  )
}
